apiVersion: v1
kind: Pod
metadata:
  name: {{ .PodName }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: {{.Name }}
    app.kubernetes.io/instance: {{ .PodName }}
    app.kubernetes.io/version: {{ .Version }}
    app.kubernetes.io/component: {{ .Component }}
    app.kubernetes.io/part-of: {{ .PartOf }}
    app.kubernetes.io/managed-by: {{ .Service }}
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    runAsUser: {{ .RunAsUser }}
  containers:
    - name: {{ .ContainerName }}
      image: {{ .Image }}
      command: ["/bin/sh", "-c", "--"]
      args: ["sleep infinity"]
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: orig-vol-mount
          mountPath: /oldData
        - name: backup-vol-mount
          mountPath: /newData
  volumes:
    - name: orig-vol-mount
      persistentVolumeClaim:
        claimName: {{.OriginalPVC}}
    - name: backup-vol-mount
      persistentVolumeClaim:
        claimName: {{.NewPVC}}